# Generated by Django 4.2.1 on 2023-05-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('escola', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nascimento', models.DateField()),
            ],
        ),
    ]
