# Generated by Django 4.2.1 on 2023-05-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='senha',
            field=models.CharField(default='123456', max_length=20),
        ),
    ]
