# Generated by Django 4.2.1 on 2023-05-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professores_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='matricula',
            field=models.CharField(default='0000000', max_length=20),
        ),
    ]
