# Generated by Django 4.2.1 on 2023-05-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_professores_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='senha_conf',
            field=models.CharField(default='123456', max_length=20),
        ),
    ]
