# Generated by Django 4.2.1 on 2023-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_professores_senha_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professores',
            name='senha_conf',
            field=models.CharField(max_length=20),
        ),
    ]
