# Generated by Django 4.2.1 on 2023-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='senha_conf',
            field=models.CharField(default='0000', max_length=15),
        ),
    ]
